db.url=jdbc:sqlserver://localhost:1433;databaseName=Manager_Edu_Project;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
db.username=sa
db.password=Thong@12345
db.pool.maximum=10

cloudinary.cloud_name=dktptmy2o
cloudinary.api_key=277421376589674
cloudinary.api_secret=obVQsUsK2wT0jlswYehW0TLEScc
cloudinary.folder=edu-project
upload.max_bytes=20971520

app.name=He thong quan ly do an sinh vien
app.page_size=20
